version: '3.8'
services:
  app:
    container_name: nodejs_app
    build: .
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/yourdbname
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data:
